version: '2'

services:
  puppet:
    container_name: puppet
    hostname: puppet
    image: puppet/puppetserver
    ports:
      - 8140
    volumes:
      - ./code:/etc/puppetlabs/code/
      - ./puppet/ssl:/etc/puppetlabs/puppet/ssl/
      - ./puppet/serverdata:/opt/puppetlabs/server/data/puppetserver/
    # In some cases unqualified hostnames can have the .local suffix
    # added, I've seen this under Docker of Mac Beta for instance.
    # Due to needing to access PuppetDB on same hostame as signed in the
    # certificate you may need to uncommant the following lines
    #environment:
    #  - PUPPETDB_SERVER_URLS=https://puppetdb.local:8081
    #links:
    #  - puppetdb:puppetdb.local

  puppetdbpostgres:
    container_name: postgres
    image: puppet/puppetdb-postgres
    environment:
      - POSTGRES_PASSWORD=puppetdb
      - POSTGRES_USER=puppetdb
    expose:
      - 5432
    volumes:
      - ./puppetdb-postgres/data:/var/lib/postgresql/data/

  puppetdb:
    hostname: puppetdb
    image: puppet/puppetdb
    ports:
      - 8080
      - 8081
    volumes:
      - ./puppetdb/ssl:/etc/puppetlabs/puppet/ssl/

  puppetboard:
    image: puppet/puppetboard
    ports:
      - 8000

  puppetexplorer:
    image: puppet/puppetexplorer
    ports:
      - 80
    read_only: true
